image: node:latest

stages:
  - test
  - build
  - deploy

before_script:
  - npm -g config set user root
  - npm install

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - echo "Running tests - With code coverage"
    - npm run cc

build:
  stage: build
  script:
    - echo "Building the app"
    - npm run build